
CREATE TABLE videojuegos (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    categoria VARCHAR(50),
    precio INT,
    estado VARCHAR(20) CHECK (estado IN ('nuevo', 'seminuevo', 'usado', 'muy usado'))
);

INSERT INTO videojuegos (nombre, categoria, precio, estado) VALUES 
('Elden Ring', 'RPG', 60, 'nuevo'),
('The Legend of Zelda: TotK', 'Aventura', 70, 'nuevo'),
('Spider-Man 2', 'Acción', 65, 'seminuevo'),
('God of War Ragnarok', 'Acción', 55, 'usado'),
('Cyberpunk 2077', 'RPG', 30, 'muy usado'),
('Hollow Knight', 'Metroidvania', 15, 'nuevo'),
('Stardew Valley', 'Simulación', 12, 'nuevo'),
('Red Dead Redemption 2', 'Aventura', 40, 'usado'),
('Grand Theft Auto V', 'Acción', 25, 'muy usado'),
('Final Fantasy VII Rebirth', 'RPG', 70, 'nuevo'),
('Baldurs Gate 3', 'RPG', 60, 'nuevo'),
('Street Fighter 6', 'Lucha', 50, 'seminuevo'),
('Resident Evil 4 Remake', 'Terror', 45, 'usado'),
('Minecraft', 'Sandbox', 20, 'nuevo'),
('Hades', 'Roguelike', 18, 'nuevo'),
('FIFA 24', 'Deportes', 30, 'usado'),
('NBA 2K24', 'Deportes', 35, 'seminuevo'),
('Gran Turismo 7', 'Conducción', 50, 'nuevo'),
('Forza Horizon 5', 'Conducción', 45, 'seminuevo'),
('It Takes Two', 'Cooperativo', 25, 'usado'),
('Sekiro: Shadows Die Twice', 'Acción', 35, 'muy usado'),
('Ghost of Tsushima', 'Aventura', 40, 'usado'),
('Horizon Forbidden West', 'Aventura', 45, 'seminuevo'),
('Ratchet & Clank: Una Dimensión Aparte', 'Plataformas', 35, 'usado'),
('Demon Souls', 'RPG', 40, 'muy usado'),
('Dark Souls III', 'RPG', 20, 'usado'),
('Bloodborne', 'RPG', 15, 'muy usado'),
('The Witcher 3: Wild Hunt', 'RPG', 25, 'usado'),
('Fallout 4', 'RPG', 10, 'muy usado'),
('Skyrim: Special Edition', 'RPG', 20, 'usado'),
('Doom Eternal', 'Shooter', 20, 'seminuevo'),
('Halo Infinite', 'Shooter', 30, 'usado'),
('Call of Duty: Modern Warfare III', 'Shooter', 60, 'nuevo'),
('Battlefield 2042', 'Shooter', 15, 'muy usado'),
('Overwatch 2', 'Shooter', 40, 'nuevo'),
('Apex Legends', 'Battle Royale', 20, 'nuevo'),
('Valorant', 'Shooter', 30, 'nuevo'),
('League of Legends', 'MOBA', 50, 'nuevo'),
('Dota 2', 'MOBA', 30, 'nuevo'),
('Starfield', 'RPG', 50, 'seminuevo'),
('Dead Space Remake', 'Terror', 40, 'usado'),
('Alan Wake 2', 'Terror', 55, 'nuevo'),
('Control', 'Acción', 15, 'usado'),
('Death Stranding', 'Aventura', 20, 'muy usado'),
('Mass Effect Legendary Edition', 'RPG', 30, 'usado'),
('Dragon Age: Inquisition', 'RPG', 10, 'muy usado'),
('Persona 5 Royal', 'RPG', 35, 'usado'),
('Nier: Automata', 'Acción RPG', 25, 'usado'),
('Cuphead', 'Plataformas', 15, 'nuevo'),
('Celeste', 'Plataformas', 10, 'nuevo'),
('Elden Ring', 'RPG', 45, 'usado'),
('Spider-Man 2', 'Acción', 50, 'usado'),
('Minecraft', 'Sandbox', 15, 'usado'),
('Hades', 'Roguelike', 10, 'muy usado'),
('FIFA 24', 'Deportes', 20, 'muy usado'),
('The Witcher 3: Wild Hunt', 'RPG', 15, 'muy usado'),
('Cyberpunk 2077', 'RPG', 25, 'usado'),
('God of War Ragnarok', 'Acción', 60, 'nuevo'),
('Baldurs Gate 3', 'RPG', 55, 'seminuevo'),
('Starfield', 'RPG', 40, 'usado');