CREATE TABLE usuarios (
    id_usuario SERIAL PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE videojuegos (
    id_videojuego SERIAL PRIMARY KEY,
    id_usuario INT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    categoria VARCHAR(50) CHECK (categoria IN ('Acción', 'Aventura', 'RPG', 'Shooter', 'Deportes', 'Lucha', 'Terror', 'Metroidvania', 'Simulación', 'Plataformas', 'Sandbox', 'MOBA')),
    precio INT CHECK (precio >= 0),
    estado VARCHAR(20) CHECK (estado IN ('nuevo', 'seminuevo', 'usado', 'muy usado')),
    FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);

INSERT INTO usuarios (nombre) VALUES  
('Carlos'), ('Marta'), ('Alejandro'), ('Lucia'), ('Javier'),  
('Sofia'), ('Daniel'), ('Elena'), ('David'), ('Pablo');

INSERT INTO videojuegos (id_usuario, nombre, categoria, precio, estado) VALUES  
(1, 'Elden Ring', 'RPG', 60, 'nuevo'),
(2, 'The Legend of Zelda: TotK', 'Aventura', 70, 'nuevo'),
(3, 'Spider-Man 2', 'Acción', 65, 'seminuevo'),
(4, 'God of War Ragnarok', 'Acción', 55, 'usado'),
(5, 'Cyberpunk 2077', 'RPG', 30, 'muy usado'),
(6, 'Hollow Knight', 'Metroidvania', 15, 'nuevo'),
(7, 'Stardew Valley', 'Simulación', 12, 'nuevo'),
(8, 'Red Dead Redemption 2', 'Aventura', 40, 'usado'),
(9, 'Grand Theft Auto V', 'Acción', 25, 'muy usado'),
(10, 'Final Fantasy VII Rebirth', 'RPG', 70, 'nuevo'),
(1, 'Baldurs Gate 3', 'RPG', 60, 'nuevo'),
(2, 'Street Fighter 6', 'Lucha', 50, 'seminuevo'),
(3, 'Resident Evil 4 Remake', 'Terror', 45, 'usado'),
(4, 'Minecraft', 'Sandbox', 20, 'nuevo'),
(5, 'Hades', 'RPG', 18, 'nuevo'),
(6, 'FIFA 24', 'Deportes', 30, 'usado'),
(7, 'NBA 2K24', 'Deportes', 35, 'seminuevo'),
(8, 'Gran Turismo 7', 'Deportes', 50, 'nuevo'),
(9, 'Forza Horizon 5', 'Deportes', 45, 'seminuevo'),
(10, 'It Takes Two', 'Plataformas', 25, 'usado'),
(1, 'Sekiro: Shadows Die Twice', 'Acción', 35, 'muy usado'),
(2, 'Ghost of Tsushima', 'Aventura', 40, 'usado'),
(3, 'Horizon Forbidden West', 'Aventura', 45, 'seminuevo'),
(4, 'Ratchet & Clank: Una Dimensión Aparte', 'Plataformas', 35, 'usado'),
(5, 'Demon Souls', 'RPG', 40, 'muy usado'),
(6, 'Dark Souls III', 'RPG', 20, 'usado'),
(7, 'Bloodborne', 'RPG', 15, 'muy usado'),
(8, 'The Witcher 3: Wild Hunt', 'RPG', 25, 'usado'),
(9, 'Fallout 4', 'RPG', 10, 'muy usado'),
(10, 'Skyrim: Special Edition', 'RPG', 20, 'usado'),
(1, 'Doom Eternal', 'Shooter', 20, 'seminuevo'),
(2, 'Halo Infinite', 'Shooter', 30, 'usado'),
(3, 'Call of Duty: Modern Warfare III', 'Shooter', 60, 'nuevo'),
(4, 'Battlefield 2042', 'Shooter', 15, 'muy usado'),
(5, 'Overwatch 2', 'Shooter', 40, 'nuevo'),
(6, 'Apex Legends', 'Shooter', 20, 'nuevo'),
(7, 'Valorant', 'Shooter', 30, 'nuevo'),
(8, 'League of Legends', 'MOBA', 50, 'nuevo'),
(9, 'Dota 2', 'MOBA', 30, 'nuevo'),
(10, 'Starfield', 'RPG', 50, 'seminuevo'),
(1, 'Dead Space Remake', 'Terror', 40, 'usado'),
(2, 'Alan Wake 2', 'Terror', 55, 'nuevo'),
(3, 'Control', 'Acción', 15, 'usado'),
(4, 'Death Stranding', 'Aventura', 20, 'muy usado'),
(5, 'Mass Effect Legendary Edition', 'RPG', 30, 'usado'),
(6, 'Dragon Age: Inquisition', 'RPG', 10, 'muy usado'),
(7, 'Persona 5 Royal', 'RPG', 35, 'usado'),
(8, 'Nier: Automata', 'RPG', 25, 'usado'),
(9, 'Cuphead', 'Plataformas', 15, 'nuevo'),
(10, 'Celeste', 'Plataformas', 10, 'nuevo'),
(1, 'Elden Ring', 'RPG', 45, 'usado'),
(2, 'Spider-Man 2', 'Acción', 50, 'usado'),
(3, 'Minecraft', 'Sandbox', 15, 'usado'),
(4, 'Hades', 'RPG', 10, 'muy usado'),
(5, 'FIFA 24', 'Deportes', 20, 'muy usado'),
(6, 'The Witcher 3: Wild Hunt', 'RPG', 15, 'muy usado'),
(7, 'Cyberpunk 2077', 'RPG', 25, 'usado'),
(8, 'God of War Ragnarok', 'Acción', 60, 'nuevo'),
(9, 'Baldurs Gate 3', 'RPG', 55, 'seminuevo'),
(10, 'Starfield', 'RPG', 40, 'usado');